name: uxx2
base: core20
version: '0.53'
summary: Single-line elevator pitch for your amazing snap
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel
confinement: strict

# plugs:
#  my-shmem-4cl:
#   interface: shared-memory
#   private: true

slots:
  my-shmem-4srv:
    interface: shared-memory
    shared-memory: my-shmem-4cl
    write: [ s.sck ]

apps:
  client:
    slots:
      - my-shmem-4srv
    command: bin/client
#    daemon: simple
  # server:
  #   plugs:
  #     - network-bind
  #   slots:
  #     - my-shmem-4srv
  #   daemon: simple
  #   command: bin/server

parts:
  snaptest:
    plugin: go
    source-type: local
    source: .
